### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by p0fi** [payliu/XcodePlus#10]
Will this awesome plugin be updated for xcode 6.2?

**Comment by powhu** [comment]
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist | xargs -IFILE defaults write FILE DVTPlugInCompatibilityUUIDs -array-add A16FF353-8441-459E-A50C-B071F53F51B7

Use this command can add XCode6.2 new UUID to all plugins.

**Comment by payliu** [comment]
now, update for Xcode 6.3.2, Thanks!
