### ISSUE TITLE
Not working in version 7.1

### ISSUE THREAD

**Issue by draskosaric** [payliu/XcodePlus#13]
It is lost from Edit menu and shortcut can not be applied.

**Comment by payliu** [comment]
already updated, thanks!

**Comment by draskosaric** [comment]
When I try to update it with alcatraz I still can't use it. But I don't see that update in your code.

**Comment by payliu** [comment]
@draskosaric , thanks for your information. I'll check Alcatraz's behavior.  

In the meantime, maybe you could try the following command, help to append new DVTPlugInCompatibilityUUID into all plug-ins of Xcode. 

```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`
```

**Comment by payliu** [comment]
Already merge develop branch into Master branch. Alcatraz should be able to be on job.
